# Generated by Django 5.0 on 2024-10-25 20:39

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=utils.fields.CustomRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='mission',
            field=utils.fields.CustomRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='vision',
            field=utils.fields.CustomRichTextField(blank=True),
        ),
    ]
