# Generated by Django 5.0 on 2024-10-25 20:51

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program_design', '0002_alter_diversitymetric_recorded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocreationworkshop',
            name='agenda',
            field=utils.fields.CustomRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='culturalsensitivityaudit',
            name='action_items',
            field=utils.fields.CustomRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='culturalsensitivityaudit',
            name='findings',
            field=utils.fields.CustomRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='culturalsensitivityaudit',
            name='recommendations',
            field=utils.fields.CustomRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inclusiontraining',
            name='description',
            field=utils.fields.CustomRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inclusiontraining',
            name='objectives',
            field=utils.fields.CustomRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='programfeedback',
            name='feedback_text',
            field=utils.fields.CustomRichTextField(blank=True),
        ),
    ]
