# Generated by Django 5.0 on 2024-10-25 20:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainability', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultingservice',
            name='consultant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consulting_services', to='users.member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultingservice',
            name='deliverables',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultingservice',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultingservice',
            name='duration',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultingservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='consultingservice',
            name='materials_included',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultingservice',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultingservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultingservice',
            name='service_type',
            field=models.CharField(choices=[('SETUP', 'Enterprise Setup'), ('TRAINING', 'Training Workshop'), ('CONSULTING', 'Consulting Package'), ('MENTORING', 'Mentoring Program')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultingservice',
            name='target_audience',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultingservice',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
