# Generated by Django 5.0 on 2024-10-25 20:51

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainability', '0003_alter_annualbudget_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatepartner',
            name='address',
            field=utils.fields.CustomRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='corporatepartner',
            name='csr_focus_areas',
            field=utils.fields.CustomRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='programreplication',
            name='implementing_partner',
            field=utils.fields.CustomRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='replicableprogram',
            name='description',
            field=utils.fields.CustomRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='replicableprogram',
            name='implementation_guide',
            field=utils.fields.CustomRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='replicableprogram',
            name='key_activities',
            field=utils.fields.CustomRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='replicableprogram',
            name='objectives',
            field=utils.fields.CustomRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='replicableprogram',
            name='resources_required',
            field=utils.fields.CustomRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='replicableprogram',
            name='target_group',
            field=utils.fields.CustomRichTextField(blank=True),
        ),
    ]
