# Generated by Django 5.0 on 2024-10-25 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('initiatives', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainstormingsession',
            name='facilitator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitated_sessions', to='users.member'),
        ),
        migrations.AddField(
            model_name='budget',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_budgets', to='users.member'),
        ),
        migrations.AddField(
            model_name='communityfeedback',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_feedback', to='users.member'),
        ),
        migrations.AddField(
            model_name='communitymapping',
            name='mapped_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapped_communities', to='users.member'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='users.member'),
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='speaking_events', to='users.member'),
        ),
        migrations.AddField(
            model_name='event',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='volunteered_events', to='users.studentvolunteer'),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_logs', to='users.member'),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='participants',
            field=models.ManyToManyField(related_name='participated_activities', to='users.member'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='initiatives.event'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_initiatives', to='users.member'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='users.department'),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='initiatives.initiative'),
        ),
        migrations.AddField(
            model_name='event',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='initiatives.initiative'),
        ),
        migrations.AddField(
            model_name='communitymapping',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_mappings', to='initiatives.initiative'),
        ),
        migrations.AddField(
            model_name='communityfeedback',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_feedback', to='initiatives.initiative'),
        ),
        migrations.AddField(
            model_name='budget',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='initiatives.initiative'),
        ),
        migrations.AddField(
            model_name='brainstormingsession',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brainstorming_sessions', to='initiatives.initiative'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='initiatives.initiative'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='responsible_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_kpis', to='users.member'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to='initiatives.milestone'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='initiatives.initiative'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='responsible_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_milestones', to='users.member'),
        ),
        migrations.AddField(
            model_name='needsanalysis',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_analyses', to='users.member'),
        ),
        migrations.AddField(
            model_name='needsanalysis',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs_analyses', to='initiatives.initiative'),
        ),
        migrations.AddField(
            model_name='risk',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='initiatives.initiative'),
        ),
        migrations.AddField(
            model_name='risk',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_risks', to='users.member'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='stakeholders',
            field=models.ManyToManyField(related_name='initiatives', to='initiatives.stakeholder'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='users.member'),
        ),
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to='initiatives.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='initiatives.initiative'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['rating'], name='initiatives_rating_c1841d_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['submitted_at'], name='initiatives_submitt_42f21c_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['date'], name='initiatives_date_02e377_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='initiatives_status_b4e94c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date'], name='initiatives_start_d_c02563_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='initiatives_event_t_9486ee_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['budget_type'], name='initiatives_budget__ba0b52_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['date_required'], name='initiatives_date_re_d862dc_idx'),
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['achieved'], name='initiatives_achieve_781ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['measurement_frequency'], name='initiatives_measure_d50c19_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['status'], name='initiatives_status_77ae07_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['target_date'], name='initiatives_target__9e78a0_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['risk_level'], name='initiatives_risk_le_ab3bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['status'], name='initiatives_status_c5db75_idx'),
        ),
        migrations.AddIndex(
            model_name='initiative',
            index=models.Index(fields=['status'], name='initiatives_status_6676b2_idx'),
        ),
        migrations.AddIndex(
            model_name='initiative',
            index=models.Index(fields=['start_date'], name='initiatives_start_d_5ae328_idx'),
        ),
        migrations.AddIndex(
            model_name='initiative',
            index=models.Index(fields=['sdg_alignment'], name='initiatives_sdg_ali_3668b4_idx'),
        ),
    ]
