# Generated by Django 5.0 on 2024-11-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0005_alter_brainstormingsession_agenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='description',
            field=models.TextField(blank=True, help_text='Describe the risk in detail'),
        ),
    ]
