# Generated by Django 4.2.16 on 2024-11-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0006_alter_risk_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, related_name='initiatives', to='initiatives.stakeholder'),
        ),
    ]
