# Generated by Django 4.2.16 on 2024-11-21 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0009_alter_budget_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='baseline_value',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
