# Generated by Django 4.2.16 on 2024-11-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0011_alter_kpi_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
