# Generated by Django 4.2.16 on 2024-11-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0012_alter_milestone_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='deliverables',
            field=models.TextField(blank=True),
        ),
    ]
