# Generated by Django 5.1.3 on 2024-12-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0014_alter_task_options_task_milestone_and_more'),
        ('users', '0002_alter_department_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='volunteer',
            field=models.ManyToManyField(related_name='initiatives', to='users.studentvolunteer'),
        ),
    ]
