# Generated by Django 5.0 on 2024-10-25 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_employmenttracking_financialtracking_skillassessment_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollectiontemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_templates', to='users.member'),
        ),
    ]
